[project]
name = "ros2_ws"
version = "0.1.0"
description = "Add a short description here"
authors = ["edvart-ros <240818@usn.no>"]
channels = ["conda-forge", "robostack-humble"]
platforms = ["win-64"]

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
pkg-config = ">=0.29.2,<0.30"
cmake = ">=3.27.4,<3.28"
make = ">=4.3,<5"
ninja = ">=1.11.1,<1.12"
colcon-common-extensions = ">=0.3.0,<0.4"
compilers = ">=1.7.0,<1.8"
vs2022_win-64 = ">=19.38.33130,<19.39"
python = ">=3.9.15,<3.10"
